import Head from 'next/head';

export default function Home() {
  return (
    <>
      <Head>
        <title>Pokedex</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
    </>
  );
}

export async function getServerSideProps(context) {
  return {
    redirect: {
      destination: '/1',
      permanent: false,
    },
  };
}
